export const controllerNames = {
  DISH_ITEMS_CONTROLLER: "DISH_ITEMS_CONTROLLER",
  CART_ITEMS_CONTROLLER: "CART_ITEMS_CONTROLLER",
  ORDER_ITEMS_CONTROLLER: "ORDER_ITEMS_CONTROLLER",
};
export const centralController = {};
